const fs = require('fs');

const elementsData = {
    aluminum: {
        en: `<b>Basic Facts</b><br>• Chemical Symbol — Al<br>• Atomic Number — 13<br>• A post-transition metal from the 13th group<br>• Most abundant metal in the Earth's crust<br>• Lightweight, silvery-white, and durable metal<br>• Non-magnetic and non-sparking<br>• Highly resistant to corrosion due to its oxide layer<br><br><b>Atomic Structure</b><br>• 13 protons in the nucleus<br>• 13 electrons around the nucleus<br>• Most common stable isotope has 14 neutrons (Aluminum-27)<br>• Electron configuration — [Ne] 3s² 3p¹<br>• Located in the 3rd period and 13th group<br><br><b>Physical Properties</b><br>• Low density (approx. 2.70 g/cm³)<br>• Boiling point — 2470°C<br>• Melting point — 660.3°C<br>• High electrical and thermal conductivity<br>• Excellent malleability and ductility<br>• Reflects about 92% of visible light<br>• Remains strong at very low temperatures<br><br><b>Chemical Properties</b><br>• Reacts with oxygen to form a thin protective Al₂O₃ layer<br>• Amphoteric: reacts with both acids and strong bases<br>• Not easily flammable in solid form, but powder is explosive<br>• Forms trivalent compounds (oxidation state +3)<br>• Reacts with halogens to form halides<br><br><b>Aluminum Isotopes</b><br>• Aluminum-27 (²⁷Al) — the only stable natural isotope<br>• Aluminum-26 (²⁶Al) — radioactive, used in radiometric dating<br>• Artificial isotopes used in scientific tracing<br><br><b>Occurrence in Nature</b><br>• Found in minerals like Bauxite and Cryolite<br>• Present in gems like Rubies and Sapphires (as Al₂O₃)<br>• Never found in free elemental form in nature<br>• Found in almost all rocks and soils<br><br><b>Industrial Production</b><br>• Hall-Héroult process (electrolysis of alumina)<br>• Bayer process (extraction from bauxite ore)<br>• Recyclable indefinitely with low energy cost<br><br><b>Applications of Aluminum</b><br>• Aerospace industry ('the winged metal')<br>• Packaging: foil, beverage cans, and containers<br>• Construction: window frames, roofs, and siding<br>• Transportation: car bodies and train components<br>• High-voltage power transmission lines<br><br><b>Significance in Science</b><br>• Fundamental for modern lightweight engineering<br>• Essential for the development of sustainable transport<br>• Key material for cryogenic technology<br><br><b>Interaction with Other Fields</b><br>• Engineering — aircraft and vehicle design<br>• Food Industry — safe packaging and utensils<br>• Construction — modern skyscrapers and bridges<br>• Energy — efficient electrical grids`,
        ru: `<b>Основные факты</b><br>• Химический символ — Al<br>• Атомный номер — 13<br>• Постпереходный металл из 13-й группы<br>• Самый распространенный металл в земной коре<br>• Легкий, серебристо-белый и прочный металл<br>• Немагнитный и не образует искр при ударе<br>• Высокая коррозионная стойкость благодаря оксидной пленке<br><br><b>Атомная структура</b><br>• 13 протонов в ядре<br>• 13 электронов вокруг ядра<br>• Самый распространенный стабильный изотоп имеет 14 нейтронов (Алюминий-27)<br>• Электронная конфигурация — [Ne] 3s² 3p¹<br>• Расположен в 3-м периоде и 13-й группе<br><br><b>Физические свойства</b><br>• Низкая плотность (около 2.70 г/см³)<br>• Температура кипения — 2470°C<br>• Температура плавления — 660.3°C<br>• Высокая электро- и теплопроводность<br>• Отличная ковкость и пластичность<br>• Отражает около 92% видимого света<br>• Сохраняет прочность при очень низких температурах<br><br><b>Химические свойства</b><br>• Реагирует с кислородом, образуя защитный слой Al₂O₃<br>• Амфотерный: реагирует как с кислотами, так и с щелочами<br>• Негорюч в слитках, но порошок взрывоопасен<br>• Образует трехвалентные соединения (степень окисления +3)<br>• Реагирует с галогенами с образованием галогенидов<br><br><b>Изотопы алюминия</b><br>• Алюминий-27 (²⁷Al) — единственный стабильный природный изотоп<br>• Алюминий-26 (²⁶Al) — радиоактивный, используется в датировании<br>• Искусственные изотопы применяются в научных исследованиях<br><br><b>Нахождение в природе</b><br>• Содержится в таких минералах, как бокситы и криолит<br>• Присутствует в драгоценных камнях, таких как рубины и сапфиры<br>• Никогда не встречается в природе в свободном виде<br>• Входит в состав почти всех горных пород и почв<br><br><b>Промышленное производство</b><br>• Процесс Холла-Эру (электролиз глинозема)<br>• Процесс Байера (извлечение из бокситовой руды)<br>• Может перерабатываться бесконечно с низкими затратами энергии<br><br><b>Применение алюминия</b><br>• Авиакосмическая промышленность («крылатый металл»)<br>• Упаковка: фольга, банки для напитков и контейнеры<br>• Строительство: оконные рамы, кровля и сайдинг<br>• Транспорт: кузова автомобилей и детали поездов<br>• Высоковольтные линии электропередач<br><br><b>Значение в науке</b><br>• Фундаментальный элемент для современного облегченного машиностроения<br>• Необходим для развития экологически чистого транспорта<br>• Ключевой материал для криогенной техники<br><br><b>Взаимодействие с другими областями</b><br>• Инженерия — проектирование самолетов и автомобилей<br>• Пищевая промышленность — безопасная упаковка и посуда<br>• Строительство — современные небоскребы и мосты<br>• Энергетика — эффективные электрические сети`,
        kk: `<b>Негізгі фактілер</b><br>• Химиялық таңбасы — Al<br>• Атомдық нөмірі — 13<br>• 13-ші топтың постөтпелі металы<br>• Жер қыртысындағы ең көп таралған металл<br>• Жеңіл, күміс түсті ақ және берік металл<br>• Беймагнитті және соққанда ұшқын шығармайды<br>• Оксидті қабықшасының арқасында коррозияға өте төзімді<br><br><b>Атомдық құрылымы</b><br>• Ядрода 13 протон<br>• Ядро айналасында 13 электрон<br>• Ең көп таралған тұрақты изотоптың 14 нейтроны бар (Алюминий-27)<br>• Электрондық конфигурациясы — [Ne] 3s² 3p¹<br>• Периодтық кестенің 3-периодында және 13-тобында орналасқан<br><br><b>Физикалық қасиеттері</b><br>• Төмен тығыздық (шамамен 2.70 г/см³)<br>• Қайнау температурасы — 2470°C<br>• Балқу температурасы — 660.3°C<br>• Жоғары электр және жылу өткізгіштік<br>• Өте жақсы соғылғыштық пен иілімділік<br>• Көрінетін жарықтың шамамен 92%-ын шағылыстырады<br>• Өте төмен температурада беріктігін сақтайды<br><br><b>Химиялық қасиеттері</b><br>• Оттегімен әрекеттесіп, жұқа қорғаныш Al₂O₃ қабатын түзеді<br>• Амфотерлі: қышқылдармен де, күшті сілтілермен де әрекеттеседі<br>• Тұтас күйінде жанбайды, бірақ ұнтағы жарылғыш келеді<br>• Үш валентті қосылыстар түзеді (тотығу дәрежесі +3)<br>• Галогендермен әрекеттесіп, галогенидтер түзеді<br><br><b>Алюминий изотоптары</b><br>• Алюминий-27 (²⁷Al) — жалғыз тұрақты табиғи изотоп<br>• Алюминий-26 (²⁶Al) — радиоактивті, радиометриялық мерзімдеуде қолданылады<br>• Жасанды изотоптар ғылыми зерттеулерде қолданылады<br><br><b>Табиғатта кездесуі</b><br>• Боксит және криолит сияқты минералдарда кездеседі<br>• Рубин мен сапфир сияқты асыл тастарда болады (Al₂O₃ түрінде)<br>• Табиғатта бос элемент түрінде ешқашан кездеспейді<br>• Барлық дерлік тау жыныстары мен топырақтарда болады<br><br><b>Өнеркәсіптік өндіріс</b><br>• Холл-Эру процесі (глинозем электролизі)<br>• Байер процесі (боксит кенінен алу)<br>• Төмен энергия шығынымен шексіз қайта өңдеуге болады<br><br><b>Алюминийдің қолданылуы</b><br>• Аэроғарыш өнеркәсібі («қанатты металл»)<br>• Қаптама: фольга, сусын банкілері және контейнерлер<br>• Құрылыс: терезе рамалары, шатырлар және сайдинг<br>• Көлік: автомобиль кузовтары мен пойыз бөлшектері<br>• Жоғары вольтты электр беру желілері<br><br><b>Ғылымдағы маңызы</b><br>• Қазіргі заманғы жеңіл машина жасаудың негізі<br>• Тұрақты көлікті дамыту үшін өте маңызды<br>• Криогендік техника үшін негізгі материал<br><br><b>Басқа салалармен өзара әрекеттесуі</b><br>• Инженерия — ұшақтар мен көліктерді жобалау<br>• Тамақ өнеркәсібі — қауіпсіз қаптама мен ыдыс-аяқ<br>• Құрылыс — заманауи зәулім ғимараттар мен көпірлер<br>• Энергетика — тиімді электр желілері`
    },
    silicon: {
        en: `<b>Basic Facts</b><br>• Chemical Symbol — Si<br>• Atomic Number — 14<br>• A metalloid from the 14th group<br>• Second most abundant element in Earth's crust (after oxygen)<br>• Hard, brittle crystalline solid with a blue-grey metallic luster<br>• Foundation of modern electronics and computing<br>• Never found free in nature; exists as silica or silicates<br><br><b>Atomic Structure</b><br>• 14 protons in the nucleus<br>• 14 electrons around the nucleus<br>• Most common stable isotope has 14 neutrons (Silicon-28)<br>• Electron configuration — [Ne] 3s² 3p²<br>• Located in the 3rd period and 14th group<br><br><b>Physical Properties</b><br>• Solid at room temperature<br>• Boiling point — 3265°C<br>• Melting point — 1414°C<br>• Semiconductor: conductivity increases with temperature<br>• Low thermal expansion and high hardness<br>• Transparent to infrared radiation<br>• Crystal structure like diamond<br><br><b>Chemical Properties</b><br>• Relatively unreactive at room temperature<br>• Forms silica (SiO₂) when heated with oxygen<br>• Reacts with halogens to form tetrahalides (e.g., SiCl₄)<br>• Forms silicides with many metals<br>• Oxidation states — +4 and -4<br>• Resistant to most acids except hydrofluoric acid<br><br><b>Silicon Isotopes</b><br>• Silicon-28 (²⁸Si) — most abundant stable isotope (92.2%)<br>• Silicon-29 (²⁹Si) — stable isotope (4.7%)<br>• Silicon-30 (³⁰Si) — stable isotope (3.1%)<br>• Used in NMR spectroscopy and semiconductor research<br><br><b>Occurrence in Nature</b><br>• Found in sand, quartz, and flint (as SiO₂)<br>• Major component of clay, granite, and many rocks<br>• Essential part of the Earth's mantle and crust<br>• Found in some biological structures like diatom shells<br><br><b>Industrial Production</b><br>• Reduction of silica with carbon in electric arc furnaces<br>• Siemens process for ultra-pure electronic-grade silicon<br>• Czochralski method for growing single-crystal ingots<br><br><b>Applications of Silicon</b><br>• Microchips, transistors, and solar cells (semiconductors)<br>• Glass and ceramic manufacturing<br>• Silicones: lubricants, sealants, and medical implants<br>• Aluminum alloys for engine blocks<br>• Concrete and brick production<br><br><b>Significance in Science</b><br>• Enabling element for the Information Age<br>• Critical for renewable energy (photovoltaics)<br>• Vital for understanding geology and planetary science<br><br><b>Interaction with Other Fields</b><br>• Electronics — CPU and memory manufacturing<br>• Energy — solar power technology<br>• Medicine — biocompatible silicone implants<br>• Construction — glass and building materials`,
        ru: `<b>Основные факты</b><br>• Химический символ — Si<br>• Атомный номер — 14<br>• Металлоид из 14-й группы<br>• Второй по распространенности элемент в земной коре (после кислорода)<br>• Твердое, хрупкое кристаллическое вещество с сине-серым блеском<br>• Основа современной электроники и вычислительной техники<br>• В природе встречается в виде кремнезема или силикатов<br><br><b>Атомная структура</b><br>• 14 протонов в ядре<br>• 14 электронов вокруг ядра<br>• Самый распространенный стабильный изотоп имеет 14 нейтронов (Кремний-28)<br>• Электронная конфигурация — [Ne] 3s² 3p²<br>• Расположен в 3-м периоде и 14-й группе<br><br><b>Физические свойства</b><br>• Твердое вещество при комнатной температуре<br>• Температура кипения — 3265°C<br>• Температура плавления — 1414°C<br>• Полупроводник: проводимость растет с температурой<br>• Низкое тепловое расширение и высокая твердость<br>• Прозрачен для инфракрасного излучения<br>• Кристаллическая структура подобна алмазу<br><br><b>Химические свойства</b><br>• Относительно инертен при комнатной температуре<br>• Образует диоксид кремния (SiO₂) при нагревании с кислородом<br>• Реагирует с галогенами с образованием тетрагалогенидов<br>• Образует силициды со многими металлами<br>• Степени окисления — +4 и -4<br>• Устойчив к большинству кислот, кроме плавиковой<br><br><b>Изотопы кремния</b><br>• Кремний-28 (²⁸Si) — самый распространенный изотоп (92.2%)<br>• Кремний-29 (²⁹Si) — стабильный изотоп (4.7%)<br>• Кремний-30 (³⁰Si) — стабильный изотоп (3.1%)<br>• Используется в ЯМР-спектроскопии и исследованиях полупроводников<br><br><b>Нахождение в природе</b><br>• Содержится в песке, кварце и кремне (в виде SiO₂)<br>• Основной компонент глины, гранита и многих горных пород<br>• Важнейшая часть мантии и коры Земли<br>• Содержится в некоторых биоструктурах, например, панцирях диатомей<br><br><b>Промышленное производство</b><br>• Восстановление кремнезема углеродом в электродуговых печах<br>• Процесс Сименса для получения сверхчистого электронного кремния<br>• Метод Чохральского для выращивания монокристаллов<br><br><b>Применение кремния</b><br>• Микросхемы, транзисторы и солнечные элементы<br>• Производство стекла и керамики<br>• Силиконы: смазки, герметики и медицинские имплантаты<br>• Алюминиевые сплавы для блоков двигателей<br>• Производство бетона и кирпича<br><br><b>Значение в науке</b><br>• Ключевой элемент информационной эпохи<br>• Важен для возобновляемой энергетики (фотовольтаика)<br>• Фундаментален для геологии и планетологии<br><br><b>Взаимодействие с другими областями</b><br>• Электроника — производство процессоров и памяти<br>• Энергетика — технологии солнечной энергии<br>• Медицина — биосовместимые силиконовые имплантаты<br>• Строительство — стекло и стройматериалы`,
        kk: `<b>Негізгі фактілер</b><br>• Химиялық таңбасы — Si<br>• Атомдық нөмірі — 14<br>• 14-ші топтың металлоиды<br>• Жер қыртысындағы ең көп таралған екінші элемент (оттегінен кейін)<br>• Көгілдір-сұр металдық жылтыры бар қатты, морт кристалды зат<br>• Қазіргі электроника мен есептеу техникасының негізі<br>• Табиғатта бос күйінде кездеспейді; кремнезем немесе силикаттар түрінде болады<br><br><b>Атомдық құрылымы</b><br>• Ядрода 14 протон<br>• Ядро айналасында 14 электрон<br>• Ең көп таралған тұрақты изотоптың 14 нейтроны бар (Кремний-28)<br>• Электрондық конфигурациясы — [Ne] 3s² 3p²<br>• Периодтық кестенің 3-периодында және 14-тобында орналасқан<br><br><b>Физикалық қасиеттері</b><br>• Бөлме температурасында қатты зат<br>• Қайнау температурасы — 3265°C<br>• Балқу температурасы — 1414°C<br>• Жартылай өткізгіш: өткізгіштігі температура жоғарылаған сайын артады<br>• Төмен жылулық кеңею және жоғары қаттылық<br>• Инфрақызыл сәулелену үшін мөлдір<br>• Алмаз сияқты кристалдық құрылым<br><br><b>Химиялық қасиеттері</b><br>• Бөлме температурасында салыстырмалы түрде инертті<br>• Оттегімен қыздырғанда кремний диоксидін (SiO₂) түзеді<br>• Галогендермен әрекеттесіп, тетрагалогенидтер түзеді<br>• Көптеген металдармен силицидтер түзеді<br>• Тотығу дәрежелері — +4 және -4<br>• Фторсутек қышқылынан басқа көптеген қышқылдарға төзімді<br><br><b>Кремний изотоптары</b><br>• Кремний-28 (²⁸Si) — ең көп таралған тұрақты изотоп (92.2%)<br>• Кремний-29 (²⁹Si) — тұрақты изотоп (4.7%)<br>• Кремний-30 (³⁰Si) — тұрақты изотоп (3.1%)<br>• ЯМР спектроскопиясында және жартылай өткізгіштерді зерттеуде қолданылады<br><br><b>Табиғатта кездесуі</b><br>• Құм, кварц және шақпақтас құрамында кездеседі (SiO₂ түрінде)<br>• Саз, гранит және көптеген тау жыныстарының негізгі компоненті<br>• Жер мантиясы мен қыртысының маңызды бөлігі<br>• Диатомей сауыттары сияқты кейбір биоқұрылымдарда кездеседі<br><br><b>Өнеркәсіптік өндіріс</b><br>• Электр доғалы пештерде кремнеземді көміртекпен тотықсыздандыру<br>• Ультра таза электронды кремний алуға арналған Сименс процесі<br>• Монокристалды кесектерді өсіруге арналған Чохральский әдісі<br><br><b>Кремнийдің қолданылуы</b><br>• Микросхемалар, транзисторлар және күн элементтері (жартылай өткізгіштер)<br>• Шыны және керамика өндірісі<br>• Силикондар: майлағыштар, герметиктер және медициналық имплантаттар<br>• Қозғалтқыш блоктарына арналған алюминий қорытпалары<br>• Бетон және кірпіш өндірісі<br><br><b>Ғылымдағы маңызы</b><br>• Ақпараттық дәуірді мүмкін еткен элемент<br>• Жаңартылатын энергия үшін өте маңызды (фотовольтаика)<br>• Геология мен планетану ғылымдарын түсіну үшін маңызды<br><br><b>Басқа салалармен өзара әрекеттесуі</b><br>• Электроника — процессор мен жад өндірісі<br>• Энергетика — күн энергиясы технологиясы<br>• Медицина — биоүйлесімді силиконды имплантаттар<br>• Құрылыс — шыны және құрылыс материалдары`
    }
};

const locales = ['en', 'ru', 'kk'];

for (const lang of locales) {
    const path = `locales/${lang}_v2.json`;
    if (!fs.existsSync(path)) continue;
    
    const locale = JSON.parse(fs.readFileSync(path, 'utf8'));
    
    // Al
    locale['system.aluminum.details'] = elementsData.aluminum[lang];
    locale['system.integumentary.details'] = elementsData.aluminum[lang];
    
    // Si
    locale['system.silicon.details'] = elementsData.silicon[lang];
    locale['system.respiratory.details'] = elementsData.silicon[lang];
    
    fs.writeFileSync(path, JSON.stringify(locale, null, 4));
    console.log(`✓ Restructured Al-Si for ${lang.toUpperCase()}`);
}
