const fs = require('fs');

const data = {
    scandium: {
        en: `<b>Basic Facts</b><br>• Chemical Symbol — Sc<br>• Atomic Number — 21<br>• A silvery-white transition metal<br>• First of the transition elements in the periodic table<br>• Rare-earth element category due to similar properties<br>• Very lightweight and high melting point<br>• Discovered in 1879 in Scandinavia<br><br><b>Atomic Structure</b><br>• 21 protons in the nucleus<br>• 21 electrons around the nucleus<br>• Most common stable isotope has 24 neutrons (Scandium-45)<br>• Electron configuration — [Ar] 3d¹ 4s²<br>• Located in the 4th period and 3rd group<br><br><b>Physical Properties</b><br>• Low density (nearly as light as aluminum)<br>• Boiling point — 2836°C<br>• Melting point — 1541°C<br>• Silvery-white appearance that turns yellowish/pinkish in air<br>• Soft metal, but hardens when alloyed with others<br>• Good thermal and electrical conductivity<br><br><b>Chemical Properties</b><br>• Reacts with water to release hydrogen gas<br>• Dissolves readily in many acids<br>• Forms a protective oxide layer in air<br>• Resembles aluminum and rare-earth metals in reactivity<br>• Common oxidation state — +3<br><br><b>Scandium Isotopes</b><br>• Scandium-45 (⁴⁵Sc) — the only stable natural isotope<br>• Scandium-46 (⁴⁶Sc) — radioactive tracer used in oil refineries<br>• Scandium-47 (⁴⁷Sc) — used in medical research and imaging<br><br><b>Occurrence in Nature</b><br>• Found in trace amounts in over 800 minerals<br>• Primary source is the mineral Thortveitite<br>• Found in the Sun and other stars<br>• Difficult to isolate in pure form from its ores<br><br><b>Industrial Production</b><br>• Byproduct of uranium and titanium processing<br>• Extracted via electrolysis of scandium chloride<br>• Produced in very small quantities globally (approx. 10-15 tons per year)<br><br><b>Applications of Scandium</b><br>• Scandium-aluminum alloys for aerospace and high-end bicycles<br>• High-intensity discharge (HID) lamps (stadium lighting)<br>• Solid oxide fuel cells (SOFCs) for efficient energy<br>• Additive in sports equipment (lacrosse sticks, baseball bats)<br><br><b>Significance in Science and Tech</b><br>• Vital for increasing strength of aluminum without increasing weight<br>• Key component in high-performance lighting technology<br>• Important in the study of early solar system materials<br><br><b>Interaction with Other Fields</b><br>• Aerospace — building stronger, lighter aircraft<br>• Energy — advanced fuel cell development<br>• Sports — high-performance equipment manufacturing<br>• Astronomy — identifying stellar compositions`,
        ru: `<b>Основные факты</b><br>• Химический символ — Sc<br>• Атомный номер — 21<br>• Серебристо-белый переходный металл<br>• Первый из переходных элементов в периодической таблице<br>• Относится к редкоземельным элементам из-за схожих свойств<br>• Очень легкий и имеет высокую температуру плавления<br>• Открыт в 1879 году в Скандинавии<br><br><b>Атомная структура</b><br>• 21 протон в ядре<br>• 21 электрон вокруг ядра<br>• Самый распространенный стабильный изотоп имеет 24 нейтрона (Скандий-45)<br>• Электронная конфигурация — [Ar] 3d¹ 4s²<br>• Расположен в 4-м периоде и 3-й группе<br><br><b>Физические свойства</b><br>• Низкая плотность (почти такой же легкий, как алюминий)<br>• Температура кипения — 2836°C<br>• Температура плавления — 1541°C<br>• Серебристо-белый вид, который желтеет или розовеет на воздухе<br>• Мягкий металл, но становится твердым в сплавах<br>• Хорошая тепло- и электропроводность<br><br><b>Химические свойства</b><br>• Реагирует с водой с выделением водорода<br>• Легко растворяется во многих кислотах<br>• Образует защитный оксидный слой на воздухе<br>• Напоминает алюминий и редкоземельные металлы по активности<br>• Типичная степень окисления — +3<br><br><b>Изотопы скандия</b><br>• Скандий-45 (⁴⁵Sc) — единственный стабильный природный изотоп<br>• Скандий-46 (⁴⁶Sc) — радиоактивный индикатор в нефтепереработке<br>• Скандий-47 (⁴⁷Sc) — используется в медицинских исследованиях и визуализации<br><br><b>Нахождение в природе</b><br>• Встречается в следовых количествах в более чем 800 минералах<br>• Основной источник — минерал тортвейтит<br>• Присутствует на Солнце и других звездах<br>• Трудно изолировать в чистом виде из руд<br><br><b>Промышленное производство</b><br>• Побочный продукт переработки урана и титана<br>• Извлекается путем электролиза хлорида скандия<br>• Производится в очень малых количествах (около 10-15 тонн в год)<br><br><b>Применение скандия</b><br>• Скандиево-алюминиевые сплавы для авиации и элитных велосипедов<br>• Металлогалогенные лампы (освещение стадионов)<br>• Твердооксидные топливные элементы (SOFC)<br>• Добавка в спортивный инвентарь (клюшки, бейсбольные биты)<br><br><b>Значение в науке и технике</b><br>• Жизненно важен для повышения прочности алюминия без утяжеления<br>• Ключевой компонент в технологии высокоэффективного освещения<br>• Важен для изучения материалов ранней Солнечной системы<br><br><b>Взаимодействие с другими областями</b><br>• Авиация — создание более легких и прочных самолетов<br>• Энергетика — разработка современных топливных элементов<br>• Спорт — производство высокотехнологичного инвентаря<br>• Астрономия — идентификация состава звезд`,
        kk: `<b>Негізгі фактілер</b><br>• Химиялық таңбасы — Sc<br>• Атомдық нөмірі — 21<br>• Күміс түсті ақ өтпелі металл<br>• Периодтық кестедегі өтпелі элементтердің біріншісі<br>• Қасиеттерінің ұқсастығына байланысты сирек жер элементтеріне жатады<br>• Өте жеңіл және балқу температурасы жоғары<br>• 1879 жылы Скандинавияда ашылған<br><br><b>Атомдық құрылымы</b><br>• Ядрода 21 протон<br>• Ядро айналасында 21 электрон<br>• Ең көп таралған тұрақты изотоптың 24 нейтроны бар (Скандий-45)<br>• Электрондық конфигурациясы — [Ar] 3d¹ 4s²<br>• Периодтық кестенің 4-периодында және 3-тобында орналасқан<br><br><b>Физикалық қасиеттері</b><br>• Төмен тығыздық (алюминий сияқты жеңіл)<br>• Қайнау температурасы — 2836°C<br>• Балқу температурасы — 1541°C<br>• Күміс түсті ақ түсті, ауада сарғыш немесе қызғылт тартады<br>• Жұмсақ металл, бірақ қорытпаларда қатаяды<br>• Жақсы жылу және электр өткізгіштік<br><br><b>Химиялық қасиеттері</b><br>• Сумен әрекеттесіп сутегі газын бөледі<br>• Көптеген қышқылдарда оңай ериді<br>• Ауада қорғаныш оксид қабатын түзеді<br>• Белсенділігі жағынан алюминий мен сирек жер металдарына ұқсайды<br>• Типтік тотығу дәрежесі — +3<br><br><b>Скандий изотоптары</b><br>• Скандий-45 (⁴⁵Sc) — жалғыз тұрақты табиғи изотоп<br>• Скандий-46 (⁴⁶Sc) — мұнай өңдеуде қолданылатын радиоактивті индикатор<br>• Скандий-47 (⁴⁷Sc) — медициналық зерттеулер мен визуализацияда қолданылады<br><br><b>Табиғатта кездесуі</b><br>• 800-ден астам минералдарда өте аз мөлшерде кездеседі<br>• Негізгі көзі — тортвейтит минералы<br>• Күнде және басқа жұлдыздарда кездеседі<br>• Кендерден таза күйінде бөліп алу қиын<br><br><b>Өнеркәсіптік өндіріс</b><br>• Уран мен титанды өңдеудің қосымша өнімі<br>• Скандий хлоридінің электролизі арқылы алынады<br>• Жаһандық деңгейде өте аз мөлшерде өндіріледі (жылына шамамен 10-15 тонна)<br><br><b>Скандийдің қолданылуы</b><br>• Аэроғарыш пен элиталық велосипедтерге арналған скандий-алюминий қорытпалары<br>• Металл-галогенді шамдар (стадиондарды жарықтандыру)<br>• Қатты оксидті отын элементтері (SOFC)<br>• Спортық жабдықтарға (лакросс таяқшалары, бейсбол битталары) арналған қоспа<br><br><b>Ғылым мен техникадағы маңызы</b><br>• Салмақты арттырмай, алюминийдің беріктігін арттыру үшін өте маңызды<br>• Жоғары тиімді жарықтандыру технологиясындағы негізгі компонент<br>• Күн жүйесінің ерте материалдарын зерттеуде маңызды<br><br><b>Басқа салалармен өзара әрекеттесуі</b><br>• Аэроғарыш — жеңілірек және берік ұшақтарды құрастыру<br>• Энергетика — заманауи отын элементтерін әзірлеу<br>• Спорт — жоғары технологиялық жабдықтар өндірісі<br>• Астрономия — жұлдыздардың құрамын анықтау`
    }
};

const locales = ['en', 'ru', 'kk'];

for (const lang of locales) {
    const path = `locales/${lang}_v2.json`;
    if (!fs.existsSync(path)) continue;
    
    const locale = JSON.parse(fs.readFileSync(path, 'utf8'));
    
    // Sc
    locale['system.scandium.details'] = data.scandium[lang];
    
    fs.writeFileSync(path, JSON.stringify(locale, null, 4));
    console.log(`✓ Restructured Scandium for ${lang.toUpperCase()}`);
}
